/**
 * build-tokens.mjs — Style Dictionary v4 multi-theme build.
 *
 * Produces, from tokens/:
 *   src/styles/tokens/base.css          :root  -> --raw-*, --p-*
 *   src/styles/tokens/theme-light.css   :root + [data-theme="light"] -> semantic vars
 *   src/styles/tokens/theme-dark.css    [data-theme="dark"]          -> semantic vars
 *   src/tokens/generated/base.tokens.ts      typed token list (raw + primitive)
 *   src/tokens/generated/semantic.tokens.ts  typed token list (light semantics)
 *
 * Semantic vars are emitted with `outputReferences: true`, so they resolve to
 * `var(--p-...)` (NOT baked literals). The raw/primitive vars live in :root
 * (base.css), so switching `data-theme` re-points the cascade with no rebuild.
 *
 * CSS var naming: raw -> --raw-*, primitive -> --p-*, semantic -> unprefixed
 * (--background-default, --text-heading, --space-md) so Tailwind @theme maps
 * cleanly.
 *
 * Run: npm run tokens:build  (gen-raw-from-tailwind runs first via `npm run tokens`)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import StyleDictionary from 'style-dictionary';

const BASE = ['tokens/raw.json', 'tokens/scale.json', 'tokens/primitives.json'];
const SHARED_SEMANTIC = ['tokens/semantics/shared.json'];
const THEMES = [
  { name: 'light', file: 'tokens/semantics/light.json', default: true },
  { name: 'dark', file: 'tokens/semantics/dark.json', default: false },
];

StyleDictionary.registerTransform({
  name: 'base/name',
  type: 'name',
  transform: (token) => {
    const p = [...token.path];
    const tier = p.shift();
    if (tier === 'raw') return ['raw', ...p].join('-');
    if (tier === 'primitive') return ['p', ...p].join('-');
    // semantic: unprefixed for clean Tailwind mapping.
    return p.join('-');
  },
});

// Typed, flat token list consumed by the doc stories.
StyleDictionary.registerFormat({
  name: 'base/ts-tokens',
  format: ({ dictionary }) => {
    const all = dictionary.unfilteredAllTokens ?? dictionary.allTokens;
    const nameByPath = new Map(all.map((t) => [t.path.join('.'), t.name]));
    const refOf = (t) => {
      const v = t.original?.value;
      if (typeof v !== 'string') return null;
      const m = v.match(/^\{(.+)\}$/);
      if (!m) return null;
      const refName = nameByPath.get(m[1]);
      return refName ? `--${refName}` : null;
    };
    const rows = dictionary.allTokens.map((t) => ({
      name: t.name,
      cssVar: `--${t.name}`,
      type: t.type ?? null,
      path: t.path,
      value: typeof t.value === 'string' ? t.value : String(t.value ?? ''),
      ref: refOf(t),
    }));
    return (
      `// Generated by scripts/build-tokens.mjs — do not edit.\n` +
      `export type DesignToken = {\n` +
      `  name: string;\n  cssVar: string;\n  type: string | null;\n` +
      `  path: string[];\n  value: string;\n  ref: string | null;\n};\n` +
      `export const tokens: DesignToken[] = ${JSON.stringify(rows, null, 2)};\n`
    );
  },
});

const TRANSFORMS = ['attribute/cti', 'base/name'];
const onlySemantic = (t) => t.path[0] === 'semantic';

async function build(config) {
  const sd = new StyleDictionary(config);
  await sd.buildAllPlatforms();
}

// 1) Base: raw + primitive -> :root
await build({
  source: BASE,
  platforms: {
    css: {
      transforms: TRANSFORMS,
      buildPath: 'src/styles/tokens/',
      files: [
        {
          destination: 'base.css',
          format: 'css/variables',
          options: { selector: ':root', outputReferences: true },
        },
      ],
    },
    ts: {
      transforms: TRANSFORMS,
      buildPath: 'src/tokens/generated/',
      files: [{ destination: 'base.tokens.ts', format: 'base/ts-tokens' }],
    },
  },
});

// 2) Per-theme: base (for reference resolution) + shared + that theme's
//    semantics, emitting ONLY semantic vars under the theme selector.
for (const theme of THEMES) {
  await build({
    source: [...BASE, ...SHARED_SEMANTIC, theme.file],
    platforms: {
      css: {
        transforms: TRANSFORMS,
        buildPath: 'src/styles/tokens/',
        files: [
          {
            destination: `theme-${theme.name}.css`,
            format: 'css/variables',
            filter: onlySemantic,
            options: {
              // The default theme also populates :root so semantic vars resolve
              // even before a data-theme is set on the document.
              selector: theme.default
                ? `:root, [data-theme="${theme.name}"]`
                : `[data-theme="${theme.name}"]`,
              outputReferences: true,
            },
          },
        ],
      },
      ...(theme.default && {
        ts: {
          transforms: TRANSFORMS,
          buildPath: 'src/tokens/generated/',
          files: [
            { destination: 'semantic.tokens.ts', format: 'base/ts-tokens', filter: onlySemantic },
          ],
        },
      }),
    },
  });
}

// Auto dark mode: re-emit the dark theme's semantic vars under
// `@media (prefers-color-scheme: dark) { :root:not([data-theme]) { … } }`, so a
// document with NO data-theme follows the OS. An explicit data-theme always
// wins (the :not() means this rule can't match once the attribute is set).
{
  const darkCss = readFileSync('src/styles/tokens/theme-dark.css', 'utf8');
  const body = darkCss.slice(darkCss.indexOf('{') + 1, darkCss.lastIndexOf('}')).trimEnd();
  const auto =
    `/* Generated by scripts/build-tokens.mjs — do not edit.\n` +
    `   Unset data-theme follows the OS; an explicit data-theme overrides this. */\n` +
    `@media (prefers-color-scheme: dark) {\n  :root:not([data-theme]) {${body}\n  }\n}\n`;
  writeFileSync('src/styles/tokens/theme-auto-dark.css', auto);
}

console.log('✓ tokens built → src/styles/tokens/, src/tokens/generated/');
