/**
 * gen-theme.mjs — generate src/styles/theme.css (Tailwind v4).
 *
 * Approach: mirror Figma's per-property semantic split exactly, with no flat
 * collapse and no invented names.
 *   1. Reset Tailwind's default color palette (--color-*: initial) → brand-only.
 *   2. Emit one custom @utility per semantic color token, mapped to its property:
 *        bg-*     ← color/bg/*     (background-color)
 *        text-*   ← color/text/*   (color)
 *        border-* ← color/border/* (border-color)
 *        fg-*     ← color/fg/*     (color — foreground/icons via currentColor)
 *      So bg-default and border-default are SEPARATE utilities reading their own
 *      split vars — no collision, exact Figma names, themed via the vars.
 *   3. radius (rounded) + fonts stay as @theme namespaces.
 *
 * No numbered ramp (primitives stay internal, like Figma).
 * Run: node scripts/gen-theme.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const color = JSON.parse(readFileSync(join(root, 'tokens/semantics/light.json'), 'utf8')).semantic.color;
const prim = JSON.parse(readFileSync(join(root, 'tokens/primitives.json'), 'utf8')).primitive;

// semantic group → [css property, utility prefix]. fg keeps Figma's name (fg-*)
// and sets `color` — the foreground color, which drives text and currentColor
// icons. (It can't be text-* because fg and text share role names.)
const PROPS = {
  bg: ['background-color', 'bg'],
  text: ['color', 'text'],
  border: ['border-color', 'border'],
  fg: ['color', 'fg'],
};

let utils = '';
let count = 0;
for (const [group, [cssProp, prefix]] of Object.entries(PROPS)) {
  for (const role of Object.keys(color[group] || {})) {
    utils += `@utility ${prefix}-${role} {\n  ${cssProp}: var(--color-${group}-${role});\n}\n`;
    count++;
  }
}

const radius = Object.keys(prim.radius)
  .map((k) => `  --radius-${k}: var(--rounded-${k});`)
  .join('\n');

const css = `/**
 * theme.css — Tailwind v4 (GENERATED by scripts/gen-theme.mjs — do not edit).
 *
 * Mirrors Figma's semantic split per-property: bg- / text- / border- / fill-
 * each read their own split var (no flat collapse, no invented names, exact roles).
 * Tailwind default color palette is reset so only brand tokens exist.
 * Exported as "@jasperlepardo/base-design-system/theme".
 */
@theme {
  /* brand-only: drop Tailwind's default color palette (keep transparent/current) */
  --color-*: initial;
}

/* ════ Semantic role utilities — per property, Figma-named, themed ════ */
${utils}
@theme {
  /* radius → rounded-* */
${radius}

  /* fonts → font-* */
  --font-sans: var(--font-family-body);
  --font-mono: var(--font-family-mono);
}
`;

writeFileSync(join(root, 'src/styles/theme.css'), css);
console.log(`✓ theme.css — ${count} per-property semantic utilities + radius/fonts (palette reset)`);
